CloudExplorer-Dev/CloudExplorer-Lite

framework/sdk/frontend/commons/router/type.ts

fix(sdk): 浏览器菜单丢失

---

framework/sdk/frontend/commons/business/person-setting/SourceChangeDialog.vue
framework/sdk/frontend/commons/router/type.ts
framework/sdk/frontend/package.json

feat(sdk): [导航/菜单] 切换角色后默认定位到当前页面  切换角色后默认跳转至当前所在页面，若切换的角色无当前页面权限则跳转至首页。

feat(sdk): [导航/菜单] 切换角色后默认定位到当前页面

---

framework/gateway/src/main/java/com/fit2cloud/gateway/config/TwtTokenAuthFilter.java
framework/gateway/src/main/java/com/fit2cloud/gateway/config/WebFluxSecurityConfig.java
framework/gateway/src/main/java/com/fit2cloud/gateway/controller/LoginController.java
framework/sdk/backend/src/main/java/com/fit2cloud/autoconfigure/SecurityConfig.java
framework/sdk/backend/src/main/java/com/fit2cloud/base/service/impl/BaseUserServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/advice/ResponseResultHandlerAdvice.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/utils/JwtTokenUtils.java
framework/sdk/backend/src/main/java/com/fit2cloud/security/SecurityDSL.java
framework/sdk/backend/src/main/java/com/fit2cloud/security/filter/JwtTokenAuthFilter.java
framework/sdk/backend/src/main/java/com/fit2cloud/security/filter/UserLoginFilter.java
framework/sdk/backend/src/main/java/com/fit2cloud/service/TokenPoolService.java
framework/sdk/frontend/commons/api/user/index.ts
framework/sdk/frontend/commons/request/index.ts
framework/sdk/frontend/commons/stores/modules/user.ts
framework/sdk/frontend/vite.config.ts

feat: 调整jwt安全  jwt续期使用与续期前同一id 退出登录后，使jwt失效

feat: 调整jwt安全

---

framework/sdk/frontend/commons/base-theme/defaultKeyValueData.ts
framework/sdk/frontend/commons/business/app-layout/index.vue
framework/sdk/frontend/commons/business/base-layout/index.vue
framework/sdk/frontend/commons/business/module-down-menu/index.vue
framework/sdk/frontend/commons/components/collapse/index.vue
framework/sdk/frontend/commons/components/layout/app-content/index.vue
framework/sdk/frontend/commons/components/layout/aside-menu/SubMenu.vue
framework/sdk/frontend/commons/components/layout/aside-start-menu/index.vue
framework/sdk/frontend/commons/components/layout/collect-menu/index.vue
framework/sdk/frontend/commons/components/layout/top-bar/index.vue
framework/sdk/frontend/commons/router/index.ts
framework/sdk/frontend/commons/router/type.ts
framework/sdk/frontend/commons/stores/modules/module.ts
framework/sdk/frontend/commons/styles/app.scss

feat(sdk): 左侧菜单UI样式调整  【ID1011737】 【导航/菜单】左侧菜单UI样式调整

feat(sdk): 左侧菜单UI样式调整

---

framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/LogServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/service/PerfMonitorService.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/BaseResourceAnalysisServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/ServerAnalysisServiceImpl.java

fix(manage-center sdk vm-service): 处理在没有监控或日志索引时，查看监控信息或者日志信息页面报错的问题<br>style(manage-center sdk vm-service): 代码格式化

fix(manage-center sdk vm-service): 处理在没有监控或日志索引时，查看监控信息或者日志信息页面报错的问题

---

services/finance-management/frontend/src/views/bill_view/components/ViewTrendChart.vue

【ID1025613】
【云账单】-费用趋势的金额显示异常，显示为NaN

fix(finance-management): 费用趋势的金额显示异常，显示为NaN

---

framework/gateway/src/main/java/com/fit2cloud/gateway/config/LoginLogAspect.java

【ID1025612】
【管理中心】-【日志】-操作日志中的操作IP没有展示客户端的IP

fix(sdk): 【日志】-操作日志中的操作IP没有展示客户端的IP

---

services/operation-analysis/frontend/src/views/base_resource_analysis/item/HostServerSpread.vue
services/operation-analysis/frontend/src/views/disk_analysis/item/DiskOrgWorkspaceSpread.vue
services/operation-analysis/frontend/src/views/server_analysis/item/CloudServerOrgWorkspaceSpread.vue

fix(operation-analysis): 鼠标悬停柱状图区域内，页面无法滑动

fix(operation-analysis): 鼠标悬停柱状图区域内，页面无法滑动

---

doc/cloudexplorer/apps/core/run-core.sh

调整模块console.log日志位置到 /opt/cloudexplorer/logs 下

pref: 调整模块console.log日志位置

---

framework/management-center/backend/src/main/java/com/fit2cloud/controller/ModuleManageController.java

fix: 上传模块权限没有限制

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/VerificationCloudAccountJob.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/CloudAccountServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/es/ElasticsearchProvide.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/platform/credential/impl/AliCredential.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/platform/credential/impl/HuaweiCredential.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/platform/credential/impl/OpenStackCredential.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/platform/credential/impl/TencentCredential.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/platform/credential/impl/VsphereCredential.java
framework/sdk/backend/src/main/java/com/fit2cloud/service/BaseSyncService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/SyncServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/api/AliyunSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/SyncProviderServiceImpl.java
services/vm-service/frontend/src/views/vm_cloud_server/monitor.vue

1.云主机监控折线图中，无监控数据的时间点断连。issues #34 
2.操作云主机，状态检查的代码优化，返回对应的错误信息。
3.云账号认证信息校验失败提示优化。

fix(sdk vm-service): 云主机监控数据展示优化,云主机状态检查优化,云账号认证信息验证提示优化

---

services/operation-analysis/frontend/src/views/base_resource_analysis/item/BaseResourceAllocationRate.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/item/BaseResourceUseRate.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/item/used_rate_item/UsedRate.vue

feat(operation-analysis): 基础资源分配率和使用率增加悬浮展示

---

services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/BaseResourceAnalysisServiceImpl.java
services/operation-analysis/frontend/src/views/base_resource_analysis/item/HostServerSpread.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/item/used_rate_item/UsedRate.vue
services/operation-analysis/frontend/src/views/disk_analysis/item/DiskOrgWorkspaceSpread.vue

fix(operation-analysis): 使用率tooltip使用率出现负数问题，修改echarts中options属性过期问题

---

framework/sdk/frontend/commons/business/base-layout/home-page/items/bill/BillTrend.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereComputeConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereDatastoreForm.vue
framework/sdk/frontend/commons/components/echart/Charts.vue
framework/sdk/frontend/commons/utils/decimalFormat.ts
framework/sdk/frontend/commons/utils/percentFormat.ts
services/finance-management/frontend/src/views/bill_detailed/index.vue
services/finance-management/frontend/src/views/bill_view/components/ViewExpensesAggsCard.vue
services/finance-management/frontend/src/views/bill_view/components/ViewTable.vue
services/finance-management/frontend/src/views/bill_view/components/ViewTrendChart.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/hostList.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/storageList.vue
services/operation-analysis/frontend/src/views/disk_analysis/diskList.vue
services/operation-analysis/frontend/src/views/resource_optimization/list.vue
services/operation-analysis/frontend/src/views/server_analysis/serverList.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java

fix(vm-service): VC虚拟机监控,读取CPU内存监控数据时，改为读取过去一个半小时的数据
feat: 调整界面数字展示

fix(vm-service): VC虚拟机监控,读取CPU内存监控数据时，改为读取过去一个半小时的数据

---

services/vm-service/frontend/src/views/vm_cloud_server/monitor.vue

revert: 暂时还原 eCharts 图表连线配置

---

framework/sdk/frontend/commons/business/module-down-menu/index.vue
framework/sdk/frontend/commons/components/layout/collect-menu/index.vue

fix(sdk): 产品服务菜单样式调整

---

services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/BaseResourceAnalysisServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java

fix(vm-service): VC存储器同步时，集群下的存储器添加返回已分配的数据

fix(vm-service): VC存储器同步时，集群下的存储器添加返回已分配的数据

---

services/vm-service/frontend/src/views/vm_cloud_server/list.vue

fix(vm-service): 云主机配置变更提交并变成成功后，云主机列表仅更新了运行状态，未更新实例规格。 #49

fix(vm-service): 云主机配置变更提交并变成成功后，云主机列表仅更新了运行状态，未更新实例规格。 #49

---

framework/management-center/backend/src/main/java/com/fit2cloud/controller/CloudAccountController.java
framework/management-center/backend/src/main/java/com/fit2cloud/controller/OrganizationController.java
framework/management-center/backend/src/main/java/com/fit2cloud/controller/WorkspaceController.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/IOrganizationService.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/IWorkspaceService.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/CloudAccountServiceImpl.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/OrganizationServiceImpl.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/WorkspaceServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/Emit.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/EventListener.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/annotaion/Emit.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/annotaion/Event.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/aspect/SimpleAspect.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/impl/EmitTemplate.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/impl/EventListenerTemplate.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/impl/SimpleElArray.java
framework/sdk/backend/src/main/java/com/fit2cloud/controller/EventController.java
services/finance-management/backend/src/main/java/com/fit2cloud/controller/BillRuleController.java
services/finance-management/backend/src/main/java/com/fit2cloud/controller/DimensionSettingController.java
services/finance-management/backend/src/main/java/com/fit2cloud/event/EventListener.java
services/finance-management/backend/src/main/java/com/fit2cloud/provider/ICloudProvider.java
services/finance-management/backend/src/main/java/com/fit2cloud/service/SyncService.java
services/finance-management/backend/src/main/java/com/fit2cloud/service/impl/SyncServiceImpl.java
services/security-compliance/backend/src/main/java/com/fit2cloud/event/EventListener.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/ISyncService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/SyncServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/event/EventListener.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/AbstractCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/ISyncProviderService.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/SyncProviderServiceImpl.java

feat(sdk,finance-management,management-center,security-compliance,vm-service): 添加事件通知机制  云账号修改名称后，在云账单中云账号的名称没有更新 #41 #81

feat(sdk,finance-management,management-center,security-compliance,vm-service): 添加事件通知机制

---

framework/sdk/frontend/commons/business/login/index.vue

fix: 登录页表单判断逻辑错误导致表单未完成时也能点击登录，出现长时间的loading

fix: 登录页表单判断逻辑错误导致表单未完成时也能点击登录，出现长时间的loading

---

framework/management-center/frontend/src/componnets/job/job_setting/CronIntervalView.vue
framework/management-center/frontend/src/componnets/job/job_setting/index.vue

feat: 【管理中心】云账号同步资源频率设置中,间隔类型的输入值限制最小时间为15分钟  issue #13

feat: 【管理中心】云账号同步资源频率设置中,间隔类型的输入值限制最小时间为15分钟

---

framework/sdk/frontend/commons/components/ce-form/items/SingleSelect.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackDiskConfigForm.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenStackDiskCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudDiskServiceImpl.java

fix: openstack创建磁盘支持不选择volumeType  issue #83

fix: openstack创建磁盘支持不选择volumeType

---

services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudImageServiceImpl.java

feat: 申请VMware主机选择模版列表增加按名称排序  issue #124

feat: 申请VMware主机选择模版列表增加按名称排序

---

services/security-compliance/backend/pom.xml
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/AliCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/api/AliInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/HuaweiCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/credential/HuaweiSecurityComplianceCredential.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/request/ListPoliciesInstanceRequest.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/request/ListVaultInstanceRequest.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/response/DiskInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentInstanceSearchFieldApi.java

feat(security-compliance): 【安全合规】-丰富合规规则种类-增加公有云云磁盘是否设置了备份策略#9

feat(security-compliance): 【安全合规】-丰富合规规则种类-增加公有云云磁盘是否设置了备份策略#9

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/job/actuator/JobActuator.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/actuator/abs/SimpleJobActuator.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/context/JobContext.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/context/StepContext.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/context/impl/SimpleJobContext.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/job/Job.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/job/SimpleJob.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/result/Result.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/result/impl/SimpleResult.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/step/JobStep.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/job/step/impl/SimpleJobStep.java
framework/sdk/backend/src/main/java/com/fit2cloud/service/BaseSyncService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/controller/ComplianceRuleController.java
services/security-compliance/backend/src/main/java/com/fit2cloud/controller/response/rule/ComplianceRuleResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/event/EventListener.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/AliCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/IJobService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/IJobStepService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/ISyncService.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/ComplianceRuleServiceImpl.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/JobServiceImpl.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/JobStepServiceImpl.java
services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/SyncServiceImpl.java
services/security-compliance/backend/src/test/java/com/fit2cloud/SyncTest.java
services/security-compliance/frontend/src/views/scan/complonents/compliance_rule/JobDetailsView.vue
services/security-compliance/frontend/src/views/scan/complonents/compliance_rule/JobStepLine.vue
services/security-compliance/frontend/src/views/scan/complonents/compliance_rule/ScanStatusColumn.vue
services/security-compliance/frontend/src/views/scan/details.vue

fix(security-compliance): 修改任务执行方式,修复部分bug  - 新建或修改合规规则后，扫描检查界面展示的合规规则的不合规资源数与扫描结果中的不合规资源数不一致 #85 - 公网IP的扫面结果列表中，IP的ID和名称展示为空 #80 - 扫描完成后，将云账号的云主机资源全部删除，再次执行扫描检查，扫描结果中依然保留已删除的资源 #84

fix(security-compliance): 修改任务执行方式,修复部分bug

---

framework/management-center/backend/src/main/java/com/fit2cloud/controller/UserController.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/IUserService.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/UserServiceImpl.java
framework/management-center/frontend/src/views/UserManage/CreateOrEdit.vue

fix: 编辑用户/编辑用户角色限制<br>fix: 查询用户/编辑用户状态/修改密码 限制

fix: 管理中心部分接口权限限制

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/utils/JsonUtil.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/AliCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/api/AliApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/api/AliInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/BucketInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/EcsInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/MongoDBInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/RdsInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/RedisInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/SecurityGroupsSecurityGroupInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/response/VpcInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/HuaweiCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/response/BucketInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/TencentCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/credential/TencentSecurityComplianceCredential.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/response/BucketInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/response/RamInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/response/SecurityGroupInstanceResponse.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/util/ResourceUtil.java

feat(security-compliance): 【安全合规】-丰富合规规则种类 针对云资源增加扫描是否打了标签 #6

feat(security-compliance): 【安全合规】-丰富合规规则种类 针对云资源增加扫描是否打了标签 #6

---

services/vm-service/backend/src/main/java/com/fit2cloud/controller/VmCloudServerController.java
services/vm-service/backend/src/main/java/com/fit2cloud/controller/request/disk/PageVmCloudDiskRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/dao/mapper/VmCloudDiskMapper.java
services/vm-service/backend/src/main/java/com/fit2cloud/dao/mapper/VmCloudServerMapper.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/IVmCloudServerService.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/PermissionServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudDiskServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerServiceImpl.java

feat(vm-service): 操作云主机增加资源可操作权限校验<br>feat(vm-service): 操作磁盘增加资源可操作权限校验

feat(vm-service): 增加资源可操作权限校验

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/form/constants/InputType.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/LineInputNumberForm.java
framework/sdk/frontend/commons/components/ce-form/items/LineNumber.vue
framework/sdk/frontend/commons/components/ce-form/items/aliyun/AliyunDiskConfigForm.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/request/AliyunVmCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/request/TencentVmCreateRequest.java
services/vm-service/frontend/src/views/vm_cloud_server/create/CeFormItem.vue
services/vm-service/frontend/src/views/vm_cloud_server/create/CreateConfirmStep.vue
services/vm-service/frontend/src/views/vm_cloud_server/grant.vue
services/vm-service/frontend/src/views/vm_cloud_server/list.vue

fix(vm-service sdk): 优化  1.创建云主机时吸底数字框样式调整 2.区分阿里云外其他云创云主机确认创建页面的样式 3.授权弹出框取消保存时关闭弹框

fix(vm-service sdk): 优化

---

framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/UsedRateSearchForm.vue
services/operation-analysis/frontend/src/views/base_resource_analysis/item/BaseResourceAllocationRate.vue

1.总览改变云账号查询条件时，基础资源分配率未更新问题
2.云主机优化建议查询策略最大值与平均值取值相反问题

fix(operation-analysis): 修复运营分析bug

---

framework/sdk/frontend/commons/components/ce-form/items/TableRadio.vue
framework/sdk/frontend/commons/components/ce-form/items/aliyun/AliyunDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/aliyun/AliyunServerInfoForm.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/request/AliyunVmCreateRequest.java
services/vm-service/frontend/src/views/vm_cloud_server/create/CeFormItem.vue

fix(vm-service ,sdk): 创建阿里云主机UI优化  1.表格显示6行内容 2.一下错别字 3.磁盘步长改为10 5.表格去掉重复label

fix(vm-service ,sdk): 创建阿里云主机UI优化

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/form/annotaion/Form.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/constants/InputType.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/util/FormUtil.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/Form.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/vsphere/ClusterForm.java
framework/sdk/frontend/commons/components/ce-form/items/LineNumber.vue
framework/sdk/frontend/commons/components/ce-form/items/Radio.vue
framework/sdk/frontend/commons/components/ce-form/items/SingleSelect.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereClusterForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereComputeConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereDatastoreForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereNetworkAdapterForm.vue
framework/sdk/frontend/commons/components/ce-form/type.ts
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereVmCreateRequest.java
services/vm-service/frontend/src/views/vm_cloud_server/create/CeFormItem.vue

feat: VMware主机申请界面UI调整

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/form/constants/InputType.java
framework/sdk/frontend/commons/base-directives/number.ts
framework/sdk/frontend/commons/components/ce-form/CeFormItem.vue
framework/sdk/frontend/commons/components/ce-form/index.vue
framework/sdk/frontend/commons/components/ce-form/items/IntNumber.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/entity/request/AliyunCreateDiskForm.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/entity/request/HuaweiCreateDiskForm.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenStackDiskCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/tencent/entity/request/TencentCreateDiskForm.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereConfigUpdateForm.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereCreateDiskForm.java
services/vm-service/frontend/src/views/vm_cloud_disk/enlarge.vue
services/vm-service/frontend/src/views/vm_cloud_server/ChangeConfig.vue

fix(vm-service): 磁盘相关bug  - 添加公有云磁盘，随实例删除选项不生效 - VMware 添加磁盘界面与设计不符 - VMware 云主机配置变更，CPU和内存可以输入小数 - 配置变更界面的UI实现与设计不符 - 磁盘扩容界面UI展示与交互逻辑与设计不符 - 配置变更界面搜索框内键入回车会退出配置变更界面并直接刷新页面

fix(vm-service): 磁盘相关bug

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/form/annotaion/Form.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/util/FormUtil.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/Form.java
framework/sdk/frontend/commons/components/ce-form/items/LineNumber.vue
framework/sdk/frontend/commons/components/ce-form/items/TableCheckbox.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackFlavorForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackNetworkConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackServerInfoForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/type.ts
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenStackServerCreateRequest.java
services/vm-service/frontend/src/views/vm_cloud_server/create/CeFormItem.vue

feat: OpenStack主机申请界面UI调整

---

framework/management-center/backend/src/main/java/com/fit2cloud/constants/PermissionConstants.java
framework/management-center/backend/src/main/java/com/fit2cloud/controller/UserController.java
framework/management-center/frontend/src/views/RoleManage/manage.vue
framework/management-center/frontend/src/views/UserManage/CreateOrEdit.vue
framework/management-center/frontend/src/views/UserManage/list.vue
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/openstack/FlavorForm.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/openstack/NetworkConfigForm.java
framework/sdk/frontend/commons/components/ce-form/items/aliyun/AliyunDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/huawei/HuaweiDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackFlavorForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackNetworkConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/openstack/OpenStackServerInfoForm.vue
framework/sdk/frontend/commons/components/ce-form/items/tencent/TencentDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereComputeConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereNetworkAdapterForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VspherePasswordInfoForm.vue
framework/sdk/frontend/commons/components/detail-page/index.vue
framework/sdk/frontend/commons/components/table-filter/OrgTreeFilter.vue
framework/sdk/frontend/commons/components/table-filter/TreeFilter.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenStackServerCreateRequest.java
services/vm-service/frontend/src/views/vm_cloud_server/create/CreateConfirmStep.vue
services/vm-service/frontend/src/views/vm_cloud_server/create/index.vue

feat: 【管理中心】【用户】-编辑用户界面，用户角色的组织/工作空间较多时展示数字TAG<br>feat: 【云主机管理】【新建云主机】选择计算资源与选择资源池统一进度条颜色<br>feat: 【云主机管理】【新建云主机】表单样式调整

feat:【管理中心/云主机管理】一些优化

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/VerificationCloudAccountJob.java

fix(management-center): 云账号校验定时任务

fix(management-center): 云账号校验定时任务

---

services/finance-management/backend/src/main/java/com/fit2cloud/service/impl/BillDimensionSettingServiceImpl.java

fix(finance-management): 账单授权错误

fix(finance-management): 账单授权错误

---

services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/AliCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/HuaweiCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiInstanceSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/tencent/TencentCloudProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereInstanceSearchApi.java

fix(security-compliance): 资源单位,同步标签,展示资源id

fix(security-compliance): 资源单位,同步标签,展示资源id

---

services/vm-service/backend/src/main/java/com/fit2cloud/dao/mapper/VmCloudDiskMapper.xml
services/vm-service/frontend/src/views/vm_cloud_disk/info.vue

fix(vm-service): 磁盘详情所属云主机未展示

---

services/finance-management/backend/src/main/java/com/fit2cloud/service/impl/BillDimensionSettingServiceImpl.java

fix(finance-management): 云账单同步错误

fix(finance-management): 云账单同步错误

---

services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/ComplianceScanServiceImpl.java

fix(security-compliance): 未正确给出对是否打了指定标签的扫描结果#169

fix(security-compliance): 未正确给出对是否打了指定标签的扫描结果#169

---

framework/sdk/frontend/commons/components/ce-form/items/LineNumber.vue
framework/sdk/frontend/commons/components/ce-form/items/huawei/HuaweiDiskConfigForm.vue
framework/sdk/frontend/commons/components/ce-form/items/tencent/TencentServerInfoForm.vue

fix(vm-service,sdk):  1.LineNumber添加change 2.腾讯云显示验证提示文字

fix(vm-service,sdk):

---

services/security-compliance/backend/src/main/java/com/fit2cloud/service/impl/ComplianceScanServiceImpl.java

fix(security-compliance): 嵌套复杂接口查询检索优化

fix(security-compliance): 嵌套复杂接口查询检索优化

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java

fix: 没有定时删除ES日志

---

services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/util/HuaweiMappingUtil.java

fix(vm-service): 华为云同步监控数据逻辑调整为批量指标查询

fix(vm-service): 华为云同步监控数据逻辑调整为批量指标查询

---

framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/LogServiceImpl.java

fix: 定时删除ES日志时间范围错误，导致会删除当天以前所有的日志

fix: 定时删除ES日志时间范围错误，导致会删除当天以前所有的日志

---

framework/sdk/backend/src/main/java/com/fit2cloud/service/PerfMonitorService.java

fix(sdk): 查询监控数据时，数据间隔获取监控数据最新一条的间隔时间

fix(sdk): 查询监控数据时，数据间隔获取监控数据最新一条的间隔时间

---

framework/sdk/backend/src/main/java/com/fit2cloud/service/PerfMonitorService.java
framework/sdk/frontend/commons/components/echart/Charts.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/entity/request/GetMetricsRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/aliyun/api/AliyunSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/api/HuaweiSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/huawei/constants/HuaweiPerfMetricConstants.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/api/OpenStackCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/tencent/api/TencentSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/VsphereCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/ConvertToPerfMetricDataVO.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/MetricTimeValue.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/util/VspherePerfMetricConstants.java
services/vm-service/frontend/src/views/vm_cloud_server/monitor.vue

fix(vm-service,sdk): vSphere 监控调整  1.调整同步监控请求参数开始时间结束时间类型 2.调整同步监控逻辑为批量指标查询以及优化同步逻辑 3.调整vmware云主机同步数据间隔为60秒 4.区分vSphere版本监控指标 5.云主机监控页面显示单位优化

fix(vm-service,sdk): vSphere 监控调整

---

framework/sdk/backend/src/main/java/com/fit2cloud/base/service/impl/BaseUserServiceImpl.java

fix: 用户修改密码增加后端接口校验

---

services/operation-analysis/frontend/src/views/optimize/list.vue

fix(operation-analysis): 云主机优化保留的小数点位数调整为统一的2位小数

fix(operation-analysis): 云主机优化保留的小数点位数调整为统一的2位小数

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/provider/impl/vsphere/utils/VsphereClient.java
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VspherePasswordInfoForm.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/AbstractCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/ICloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/VsphereCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereVmCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/util/VsphereVmClient.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerServiceImpl.java

feat: 创建VMware云主机支持设置密码

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/form/constants/InputType.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/form/vo/vsphere/TemplateForm.java
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereServerInfoForm.vue
framework/sdk/frontend/commons/components/ce-form/items/vsphere/VsphereTemplateSelectForm.vue
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereVmCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/util/VsphereVmClient.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/SyncProviderServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerServiceImpl.java
services/vm-service/frontend/src/locales/lang/en.ts
services/vm-service/frontend/src/locales/lang/zh-cn.ts
services/vm-service/frontend/src/locales/lang/zh-tw.ts
services/vm-service/frontend/src/views/vm_cloud_server/info.vue
services/vm-service/frontend/src/views/vm_cloud_server/list.vue

feat: 创建VMware云主机选择模板可以看到模板的备注信息<br>feat: 创建VMware云主机支持添加备注, 列表可以查看备注

feat: 创建云主机时模板和云主机支持显示和设置“备注”字段

---

framework/sdk/frontend/commons/api/optimize/index.ts
framework/sdk/frontend/commons/base-directives/number.ts
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/CreateOrEdit.vue
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/RuleItem.vue
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/ServerList.vue
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/ServerOptimization.vue
framework/sdk/frontend/commons/request/index.ts
services/operation-analysis/backend/src/main/java/com/fit2cloud/dto/optimization/VmCloudServerExcelDTO.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/CloudServerOptimizationServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationRuleFieldProviderImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyIgnoreResourceServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/utils/CustomCellWriteHeightConfig.java
services/operation-analysis/backend/src/main/resources/db/migration/V3_1__ddl_create_optimization_strategy_ignore_resource.sql
services/operation-analysis/frontend/src/views/optimization_strategy/list.vue
services/operation-analysis/frontend/src/views/optimize/list.vue
services/vm-service/backend/src/main/java/com/fit2cloud/service/IVmCloudServerStatusTimingService.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/SyncProviderServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerStatusTimingServiceImpl.java
services/vm-service/backend/src/main/resources/db/migration/V10_0__ddl_create_vm_cloud_server_status_timing.sql

fix(operation-analysis vm-service sdk): 优化策略管理bug修复  云主机优化 1.导出按钮调整为图标 2.导出空文件(done) 3.分析数据范围限制为5年1825天(done) 4.数字框无法清空输入新值(done) 5.操作列调整，调小(done) 6.下载问题 等问题 优化策略 1.操作列按钮调整，去掉垃圾按钮(done) 2.优化规则去掉最小值(done) 3.修改优化策略规则时，监控字段回变为数据库字段（done） 4.设置忽略资源步骤资源列表搜索 等问题 云主机 同步云主机时初始化开关机状态时间逻辑调整

fix(operation-analysis vm-service sdk): 优化策略管理bug修复

---

framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/CreateOrEdit.vue
services/operation-analysis/backend/src/main/java/com/fit2cloud/controller/OptimizationStrategyController.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/IOptimizationStrategyIgnoreResourceService.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyIgnoreResourceServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyServiceImpl.java

fix(operation-analysis sdk): 优化策略管理bug修复

fix(operation-analysis sdk): 优化策略管理bug修复

---

framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/CloudAccountServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/autoconfigure/ThreadPoolConfig.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/event/impl/EmitTemplate.java
services/finance-management/backend/src/main/java/com/fit2cloud/service/impl/BillingPolicyServiceImpl.java

fix: 启动一段时间后，项目内部多线程/跨模块调用401

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java
framework/management-center/frontend/src/views/OperatedLog/AllOperatedLogList.vue
framework/management-center/frontend/src/views/OperatedLog/DiskOperatedLogList.vue
framework/management-center/frontend/src/views/OperatedLog/LoginLogList.vue
framework/management-center/frontend/src/views/OperatedLog/VmOperatedLogList.vue
framework/management-center/frontend/src/views/SystemLog/list.vue
framework/sdk/frontend/commons/api/optimize/index.ts
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/CreateOrEdit.vue
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/ServerOptimization.vue
services/operation-analysis/backend/src/main/java/com/fit2cloud/constants/MenuConstants.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/controller/OptimizationStrategyController.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/controller/OptimizationStrategyResourceController.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/CloudServerOptimizationServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/DiskAnalysisServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyIgnoreResourceServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationStrategyServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/ServerAnalysisServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/utils/cache/ElasticSearchVmLatestMonitoringDataSyncCache.java
services/operation-analysis/backend/src/main/resources/db/migration/V3_0__ddl_create_optimization_strategy.sql
services/operation-analysis/backend/src/main/resources/db/migration/V3_1__ddl_create_optimization_strategy_ignore_resource.sql
services/operation-analysis/frontend/src/views/optimize/list.vue
services/operation-analysis/frontend/src/views/server_analysis/baseView.vue

fix(operation-analysis sdk): 运营分析bug修复

fix(operation-analysis sdk): 运营分析bug修复

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/constants/ChargeTypeConstants.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/provider/impl/openstack/OpenStackBaseCloudProvider.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/provider/impl/vsphere/VsphereBaseCloudProvider.java
framework/sdk/backend/src/main/java/com/fit2cloud/controller/BaseBillingPolicyController.java
services/finance-management/backend/src/main/java/com/fit2cloud/controller/BillingPolicyController.java
services/finance-management/backend/src/main/java/com/fit2cloud/controller/request/CalculateConfigPriceRequest.java
services/finance-management/backend/src/main/java/com/fit2cloud/service/IBillingPolicyService.java
services/finance-management/backend/src/main/java/com/fit2cloud/service/impl/BillingPolicyServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/OpenStackCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/api/OpenStackCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/constants/OpenstackPeriodOption.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenStackServerCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/openstack/entity/request/OpenstackCalculateConfigPriceRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/VsphereCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/api/VsphereSyncCloudApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/constants/VspherePeriodOption.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereCalculateConfigPriceRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/vsphere/entity/request/VsphereVmCreateRequest.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudDiskServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/utils/ChargingUtil.java

feat(vm-service): 私有云虚拟机创建添加付费类型,询价

feat(vm-service): 私有云虚拟机创建添加付费类型,询价

---

framework/management-center/frontend/src/api/cloud_account/index.ts
framework/management-center/frontend/src/api/module/index.ts
framework/management-center/frontend/src/api/organization/index.ts
framework/management-center/frontend/src/api/user/index.ts
framework/management-center/frontend/src/api/workspace/index.ts
framework/sdk/frontend/commons/api/cloud_account/index.ts
framework/sdk/frontend/commons/api/form_resource_api/index.ts
framework/sdk/frontend/commons/api/optimize/index.ts
framework/sdk/frontend/commons/api/organization/index.ts
framework/sdk/frontend/commons/api/system_parameter/index.ts
framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/CreateOrEdit.vue
services/finance-management/frontend/src/views/billing_policy/components/CloudAccountCheckbox.vue
services/security-compliance/frontend/src/api/rule/index.ts
services/security-compliance/frontend/src/api/rule_group/index.ts
services/vm-service/frontend/src/api/recycle_bin/index.ts
services/vm-service/frontend/src/api/vm_cloud_disk/index.ts
services/vm-service/frontend/src/api/vm_cloud_server/index.ts

fix: 部分前端API调用404<br>Merge remote-tracking branch 'origin/main'

fix: frontend api 404

---

services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/CloudServerOptimizationServiceImpl.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/OptimizationRuleFieldProviderImpl.java

fix(operation-analysis): 运营分析bug修复

fix(operation-analysis): 运营分析bug修复

---

services/operation-analysis/backend/src/main/java/com/fit2cloud/dto/optimization/VmCloudServerExcelDTO.java
services/operation-analysis/backend/src/main/java/com/fit2cloud/service/impl/CloudServerOptimizationServiceImpl.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerStatusTimingServiceImpl.java

fix(operation-analysis,vm-service): 1.建议回收优化策略查询待回收资源无数据问题。2.同步云主机时，更新云主机开关机状态时长表逻辑调整。

fix(operation-analysis,vm-service): 1.建议回收优化策略查询待回收资源无数据问题。2.同步云主机时，更新云主机开关机状态时长表逻辑调整。

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java

fix(management-center): 清理数据任务问题修改，清理月分小于1个月时，被设置成了清理3个月的。

fix(management-center): 清理数据任务问题修改，清理月分小于1个月时，被设置成了清理3个月的。

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/LogServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/es/ElasticsearchProvide.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/utils/DateUtil.java
services/vm-service/backend/src/main/java/com/fit2cloud/controller/VmCloudServerController.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/IVmCloudServerService.java
services/vm-service/backend/src/main/java/com/fit2cloud/service/impl/VmCloudServerServiceImpl.java

fix(management-center vm-service sdk): 1.清理日志监控定时任务调整为每30分钟执行一次（测试）2.清理判定字段区分日志或者是监控数据3.查看已删除云主机的详情为空问题。

fix(management-center vm-service sdk): 1.清理日志监控定时任务调整为每30分钟执行一次（测试）2.清理判定字段区分日志或者是监控数据3.查看已删除云主机的详情为空问题。

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/LogServiceImpl.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/es/ElasticsearchProvide.java

fix(management-center sdk): 清理日志监控定时任务调整为每10分钟执行一次（测试)

fix(management-center sdk): 清理日志监控定时任务调整为每10分钟执行一次（测试)

---

framework/management-center/backend/src/main/java/com/fit2cloud/quartz/LogCleanJob.java

fix(management-center sdk): 清理日志监控数据定时任务时间调整为每天01:30

fix(management-center sdk): 清理日志监控数据定时任务时间调整为每天01:30

---

framework/sdk/frontend/commons/business/base-layout/home-page/items/operation/optimize/RuleItem.vue

fix(sdk): 运营分析，编辑优化策略页面样式优化

---

services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/ActionApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/SyncApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/util/MappingUtil.java

fix(vm-service): proxmox 同步没有集群的虚拟机失败,同步磁盘失败

fix(vm-service): proxmox 同步没有集群的虚拟机失败,同步磁盘失败

---

README.md
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/ActionApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/SyncApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/util/MappingUtil.java

fix(vm-service): proxmox 同步没有集群的虚拟机失败,同步磁盘失败

Pr@main@fix vm sync

---

framework/management-center/backend/src/main/java/com/fit2cloud/controller/ModuleManageController.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/IModuleManageService.java
framework/management-center/backend/src/main/java/com/fit2cloud/service/impl/ModuleManageServiceImpl.java
framework/management-center/frontend/src/api/module/index.ts
framework/management-center/frontend/src/views/ModuleManage/ModuleManagePage.vue

feat: 调整安装/升级模块接口需要的参数

---

framework/sdk/backend/src/main/java/com/fit2cloud/common/provider/entity/F2CBasePerfMetricMonitorData.java
framework/sdk/backend/src/main/java/com/fit2cloud/common/provider/entity/F2CPerfMetricMonitorData.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/ProxmoxCloudProvider.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/SyncApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/constants/ProxmoxPerfMetricConstants.java
services/vm-service/frontend/src/views/vm_cloud_server/monitor.vue

fix(vm-service): proxmox虚拟机监控

---

services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/SyncApi.java
services/vm-service/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/util/MappingUtil.java

fix(vm-service): proxmox创建虚拟机 没有集群失败

fix(vm-service): proxmox创建虚拟机 没有集群失败

---

services/security-compliance/backend/src/main/java/com/fit2cloud/provider/constants/F2CDiskStatus.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/entity/response/F2CDatastore.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/entity/response/F2CDisk.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/entity/response/F2CHost.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/entity/response/F2CVirtualMachine.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/ProxmoxProvider.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/ProxmoxApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/api/ProxmoxSearchFieldApi.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/entity/credential/ProxmoxComplianceCredential.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/entity/request/ProxmoxBaseRequest.java
services/security-compliance/backend/src/main/java/com/fit2cloud/provider/impl/proxmox/util/MappingUtil.java
services/security-compliance/frontend/src/views/rule/ComplianceRule.vue
services/security-compliance/frontend/src/views/rule/components/CreateComplianceRule.vue
services/security-compliance/frontend/src/views/rule/components/UpdateComplianceRule.vue
services/security-compliance/frontend/src/views/scan/complonents/compliance_rule/ScanStatusColumn.vue
services/security-compliance/frontend/src/views/scan/complonents/compliance_rule/index.vue

feat(security-compliance): 支持proxmox, ECS,DISK,HOST,DATASTORE资源扫描

feat(security-compliance): 支持proxmox, ECS,DISK,HOST,DATASTORE资源扫描

---

framework/gateway/src/main/java/com/fit2cloud/gateway/controller/LoginController.java
framework/management-center/backend/src/main/java/com/fit2cloud/controller/UserController.java
framework/sdk/backend/src/main/java/com/fit2cloud/controller/BaseUserController.java

feat: 用户相关接口隐藏密码字段返回值
